- src/pages/component/condition/condition.vue
> fix: center conditional search button

- src/pages/plugin/article/article.vue
> refactor: delete console.log

- src/pages/Words/PronunciationUpload/PronunciationUpload.vue
> fix: fix style in PronunciationUpload.Vue

- src/pages/component/daily/daily.vue
- src/pages/component/pinyin/pinyin.vue
> feat: add navigation

- src/pages/plugin/home/home.vue
> feat: change style in plugin/home.Vue

- src/pages/component/condition/condition.vue
> fix: fix error navigating

- src/colorui/components/cu-custom.vue
> fix: fix words' position in navigation

- src/pages/about/visitor/visitor.vue
- src/pages/component/voice/voice.vue
> fix: fix visitor interface bugs

- src/pages/plugin/article/article.vue
> fix: fix scroll-view in comment section

- src/colorui/components/cu-custom.vue
- src/pages/about/articlesliked/articlesliked.vue
- src/pages/about/myarticles/myarticles.vue
- src/pages/about/mycomments/mycomments.vue
- src/pages/component/voice/voice.vue
- src/pages/plugin/article/article.vue
> feat: add words in blank screen

- src/pages/basics/search/search.vue
> fix: fix the format of pinyin

- src/components/ArticleComment.vue
- src/pages/plugin/comment/comment.vue
> refactor: refactor comment page

- src/components/ArticleComment.vue
- src/pages/plugin/article/article.vue
- src/pages/plugin/comment/comment.vue
> fix: fix the bottom divider of comment

- src/pages/login/login.vue
> fix: fix the style of login page

- src/pages.json
- src/pages/component/RandomQuiz/RandomQuiz.vue
- src/pages/component/SearchQuiz/SearchQuiz.vue
- src/pages/component/home/home.vue
- src/pages/component/quiz/quiz.vue
- src/pages/component/quizzes/quizzes.vue
- src/routers/index.js
- src/services/quiz.js
> feat: add new quiz function

- package.json
- src/pages/plugin/article/article.vue
- src/pages/plugin/home/home.vue
- src/services/article.js
- src/services/website.js
> refactor: refactor plugin home page

- src/pages/basics/characters/characters.vue
- src/pages/basics/search/search.vue
- src/pages/basics/words/words.vue
- src/pages/component/RandomQuiz/RandomQuiz.vue
- src/pages/component/condition/condition.vue
- src/pages/component/daily/daily.vue
- src/pages/component/pinyin/pinyin.vue
- src/pages/component/quiz/quiz.vue
- src/pages/component/quizzes/quizzes.vue
- src/pages/plugin/article/article.vue
> feat: add share function

- src/pages/component/SearchQuiz/SearchQuiz.vue
- src/pages/component/quiz/quiz.vue
- src/services/quiz.js
> fix: fix the url

- src/pages/about/myarticles/myarticles.vue
- src/pages/plugin/home/home.vue
> refactor: refactor articleslist component

- src/components/ArticleComment.vue
- src/pages/component/RandomQuiz/RandomQuiz.vue
- src/pages/component/quiz/quiz.vue
- src/pages/plugin/article/article.vue
- src/pages/plugin/comment/comment.vue
> refactor: adjust logic in quiz page

- src/pages/component/RandomQuiz/RandomQuiz.vue
- src/pages/component/quiz/quiz.vue
> feat: change quiz‘s options marks

- src/components/ArticleList.vue
- src/pages/about/articlesliked/articlesliked.vue
- src/pages/plugin/home/home.vue
> fix: fix the style in myarticles

- src/pages/basics/search/search.vue
- src/pages/component/RandomQuiz/RandomQuiz.vue
- src/pages/component/SearchQuiz/SearchQuiz.vue
- src/pages/component/quiz/quiz.vue
- src/pages/component/quizzes/quizzes.vue
- src/utils/u-parse/components/IFramePlayer.vue
> fix: fix errors in SearchQuiz pages

- src/pages/basics/search/search.vue
- src/pages/plugin/home/home.vue
- src/services/article.js
- src/services/character.js
- src/services/word.js
fix character pages
refactor article pages
close #80
> fix: fix search pages

- src/services/article.js
> fix: fix article searching service

- src/pages/about/email/email.vue
- src/pages/about/home/home.vue
- src/pages/about/nickname/nickname.vue
- src/pages/about/password/password.vue
- src/pages/about/phone/phone.vue
- src/pages/about/userinfo/userinfo.vue
- src/routers/index.js
- src/services/user.js
- src/services/website.js
> refactor: refactor userInfo pages

- src/pages.json
- src/pages/component/RandomQuiz/RandomQuiz.vue
- src/pages/component/poster/poster.vue
- src/pages/component/quizzes/quizzes.vue
- src/pages/component/test/test.vue
- src/routers/index.js
> feat: add test function

- src/pages/basics/home/home.vue
- src/pages/index/index.vue
- src/routers/index.js
- src/services/login.js
- src/services/website.js
- src/utils/request.js
> refactor: refactor home page

- src/App.vue
- src/pages/about/email/email.vue
- src/pages/about/home/home.vue
- src/pages/about/userinfo/userinfo.vue
- src/pages/about/visitor/visitor.vue
- src/pages/basics/characters/characters.vue
- src/pages/basics/pronunciation/pronunciation.vue
- src/pages/basics/word/word.vue
- src/pages/component/condition/condition.vue
- src/pages/component/daily/daily.vue
- src/pages/component/pinyin/pinyin.vue
- src/pages/component/voice/voice.vue
- src/pages/forget/forget.vue
- src/pages/register/register.vue
- src/services/article.js
- src/services/character.js
- src/services/login.js
- src/services/pronunciation.js
- src/services/user.js
- src/services/website.js
- src/services/word.js
close #12
还剩下两个 `globalData.server` 已经在 #109 中处理了
> refactor: refactor globalData

- src/App.vue
- src/pages/basics/home/home.vue
- src/pages/index/index.vue
> fix: add redirect tips

- src/pages.json
- src/pages/component/VoiceRankList/VoiceRankList.vue
- src/pages/component/home/home.vue
- src/pages/component/voice/voice.vue
- src/routers/index.js
- src/services/pronunciation.js
feat(voice): add VoiceRankList
close #97
> 增加用户语音上传榜单

- src/pages/component/home/home.vue
- src/pages/component/voice/voice.vue
close #121 
fix(voice): fix voice showing
> 修正个人语音界面语音显示问题

- src/pages/tools/quiz/test/test.vue
fix(test): fix key bindings
close #123
> 修正试卷页面key绑定表达式

- src/services/user.js
fix: fix exit login
close #127
> 修正退出登录清理登陆状态的问题

- src/App.vue
fix: fix navigation to other platforms
close #126
> 修正横屏自动跳转失效

- src/components/ArticleList.vue
- src/pages.json
- src/pages/about/visitor/visitor.vue
- src/pages/basics/words/words.vue
- src/pages/plugin/home/home.vue
- src/pages/search.vue
- src/pages/users/detail.vue
- src/routers/index.js
fix(visitor): fix visitor image showing
close #128
> 修正并完善用户详情页面

- src/pages/search.vue
feat(search): add search history function
close #112
> 添加搜索页面的历史记录功能

- src/pages/about/userinfo/userinfo.vue
fix(user): fix userInfo avatar
close #132
> 修正个人信息界面上传头像

- src/pages/articles/edit.vue
close #139
fix(article): add min-height for artcile description
> 添加文章编辑界面描述输入框最低高度

- src/pages/articles/details.vue
- src/routers/article.js
fix(wechat): close publish modules
> 在微信小程序中关闭发布功能

- src/pages/index.vue
- src/utils/request.js
refactor(login): improve login logic
> 首页登录直接跳转至登录页

- src/pages.json
- src/pages/users/settings/information.vue
- src/pages/users/settings/nickname.vue
- src/pages/users/settings/password.vue
- src/pages/users/settings/telephone.vue
- src/routers/user.js
- src/services/user.js
fix(user): fix redirect of user settings
> 修复用户设置跳转失败

- src/pages/users/me.vue
- src/pages/words/details.vue
- src/pages/words/pronunciations/upload.vue
- src/routers/index.js
- src/services/file.js
- src/utils/clipboard.js
feat(word): add tips in word details
> 增加词语详情的文字提示

- .eslintrc.js
- src/pages.json
- src/pages/login/forget.vue
- src/pages/login/mixin/getCodeMixin.js
- src/pages/login/register.vue
- src/services/website.js
对输入的邮箱进行验证，并且阻止用户连续发送验证码 close #23
> feat: prevent continuous sending of codes

- src/pages/words/pronunciations/ranking.vue
feat(words): add my rank and amount of voice
close #135
> 语音排行榜增加我的排名和语音量

- src/pages/tools/index.vue
fix(tools): fix scroll-view in tools page
close #172
> 修复工具页面滚动问题

- package-lock.json
- src/pages.json
- src/pages/quizzes/tests/answer.vue
- src/pages/quizzes/tests/score.vue
在H5上，阻止用户没有真正做题而跳到海报页面，并在H5上隐藏了分享和保存海报两个按钮
在海报页面展示用户的头像和昵称
close #120
> feat: show userinfo on poster

- src/App.vue
- src/pages/login/register/wechat.vue
- src/pages/users/settings/information.vue
- src/services/file.js
- src/services/user.js
> fix(login): fix wechat register

- src/pages/login/login.vue
> refactor(login): remove normal register in mp-weixin

- src/pages/articles/comments/details.vue
- src/pages/articles/details.vue
- src/pages/articles/index.vue
- src/services/login.js
> fix: disable buttons when not logged in
